version: "2"

services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      # - './extras/web-interface/dist:/usr/share/jellyfin/web:ro'
      - ${JF_CONFIG_PATH}:/config
      - ${TV_PATH}:/data/tvshows
      - ${MOVIES_PATH}:/data/movies
      - ${BOOKS_PATH}:/data/books
      - ${COMICS_PATH}:/data/comics
      - ${MUSIC_PATH}:/data/music
      - ${ANIME_PATH}:/data/anime
      - ${ANIME_MOVIES_PATH}:/data/anime_movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: always

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${TV_PATH}:/tv
      - ${ANIME_PATH}:/anime
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${MOVIES_PATH}:/movies
      - ${ANIME_MOVIES_PATH}:/anime_movies
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 7878:7878
    restart: always

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BAZARR_CONFIG_PATH}:/config
      - ${MOVIES_PATH}:/movies
      - ${ANIME_MOVIES_PATH}:/anime_movies
      - ${ANIME_PATH}:/anime
      - ${TV_PATH}:/tv
    ports:
      - 6767:6767
    restart: always

  mylar3:
    image: linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MYLAR3_CONFIG_PATH}:/config
      - ${COMICS_PATH}:/comics
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 8090:8090
    restart: always

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${READARR_CONFIG_PATH}:/config
      - ${BOOKS_PATH}:/books
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 8787:8787
    restart: always

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIDARR_CONFIG_PATH}:/config
      - ${MUSIC_PATH}:/music
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 8686:8686
    restart: always

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    ports:
      - 9696:9696
    restart: always

  unmanic:
    image: josh5/unmanic
    container_name: unmanic
    ports:
    -  8888:8888
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
    - ${UNMANIC_CONFIG_PATH}/config:/config
    - ${UNMANIC_TRANSCODE_PATH}:/tmp/unmanic
    - ${UNMANIC_OUTPUT_PATH}:/library/output
    - ${TRANSCODE_TEST_PATH}:/library/test

    # Media Paths
    - ${TV_PATH}:/library/tvshows
    - ${MOVIES_PATH}:/library/movies
    - ${MUSIC_PATH}:/library/music
    - ${ANIME_PATH}:/library/anime
    - ${ANIME_MOVIES_PATH}:/library/anime_movies

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ${QBITTORRENT_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: always
    # username/password is admin/adminadmin

  server:
    image: nginx
    restart: always
    container_name: mediaserver
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80